# -*- coding: utf-8 -*-
"""python3_ayushi3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjgVXZWp-G6ys-YyPeIfWUBN1xNrFeE1

# Lists

## Lists
- A list is a collection of items, that is stored in a variable. 
- The items should be related in some way, but there are no restrictions on what can be stored in a list.

### Syntax
list-name = [list of comma seperated values]

### Slicing with list

index start with 0

 listname[index_number]

 listname[start_index:end_index]

 listname[:end_index]

 listname[start_index:]


negative index: 
 listname[:-index] 


### list methods
- append()
- len()
- insert(index,value)
- sort()
- reverse()
- pop(), pop(index)
- min(), max(), sum()


We can change the contents of the lists after its creation

listname[index]=newvalue

#### Task 1: Run below code and try to make some changes to the code
"""

# list creation
countries = ['Africa', 'Australia', 'USA', 'China']

# print whole list
print(countries)

# Accessing list elements
print("Value at 0 index: ",countries[1])

# assignning new value to index
countries[0]='Japan'

print("New value at index 0: ",countries[0])

#Changes made by me
print(countries[0:])
print(countries[:2])

"""### Iterating lists

#### Task 2: Run below code and try to make some changes to the code
"""

lists=['flower','abc',6,'Semester']

print(lists)

# we can access the elements of list using loops

for item in lists:
    print(item)

#Changes made by me
lists[1] = 'Aryan'

print("New value at index 1: ",lists[1])

#New iteration
for i in lists:
    print(i)

"""#### Task 3: Run below code and try to make some changes to the code"""

# print the index number with value

countries = ['japan', 'China', 'USA']

for index, country in enumerate(countries):
    place = str(index)
    print("Index: " + place + ", Value: " + country.title())
    
# find index of
index = countries.index('USA') 
print("\n Index of USA is: ",index)

#Changes made by me 
countries[1] = 'India'

for index, country in enumerate(countries):
    place = str(index)
    print("Index: " + place + ", Value: " + country.title())

# find index of
index = countries.index('India') 
print("\n Index of India is: ",index)

"""#### Task 4: Run below code and try to make some changes to the code"""

# Remove the last country from the list by index or by value
countries = ['japan', 'China', 'USA']

del countries[1]

print(countries)

#Changes made by me

del countries[1]

print(countries)

"""### List comprehension (with for loop)

#### Task 5: Run below code and try to make some changes to the code
"""

# without comprehension

cubes = []
for x in [1, 2, 3, 4, 5]:
    cubes.append(x ** 3) 
    
print(cubes)

#Changes made by me
pow4 = []
for x in [1, 2, 3, 4, 5]:
    pow4.append(x ** 4) 
    
print(pow4)

# with comprehension
  
cubes= [x**3 for x in [1, 2, 3, 4, 5]]
print(cubes)

#Changes made by me
  
pow5= [x**5 for x in [1, 2, 3, 4, 5]]
print(pow5)

numbers=[1,2,3,4,5,6,7,8,9,10]
list=[x for x in numbers]
list

"""#### Program 1: Write a python program which does the following
- Make a list that includes four job types , such as 'programmer', 'truck driver' and so on
- Use the *list.index()* function to find the index of one job type in your list.
- Use the *in* function to show that this job type is in your list.
- Use the *append()* function to add a new job type to your list.
- Use the *insert()* function to add a new job type "Python Programmer" at the beginning of the list.
- Use a loop to show all the job types in your list.
"""

mlist = ['programmer','truckdriver','scientist','docotr']

"""#### Problem 2: Write a python program for following

- Make a list that includes the names of five famous people.
- Remove each person from the list, one at a time, using the four methods given below:
    - Del item from the list by del: del listname[index]
    - Remove the item from the list by remove method: listname.remove('itemname')
    - Using pop() method, It removes the last item from the list: listname.pop() 
    - Pop any item from the list by index: listname: listname.pop(index)
- Print out a message that there are no famous people left in your list, and print your list to prove that it is empty.
"""



"""#### Program 3: Write a python program which does the following

- Store the first ten letters of the alphabet in a list.
- Use a slice to print out the first three letters of the alphabet.
- Use a slice to print out any three letters from the middle of your list.
- Use a slice to print out the letters from any point in the middle of your list, to the end.
"""



"""#### Program 4: Write a python program for following

- Your goal in this exercise is to prove that copying a list protects the original list.
- Make a list with three people's names in it.
- Use a slice to make a copy of the entire list.
- Add at least two new names to the new copy of the list.
- Make a loop that prints out all of the names in the original list, along with a message that this is the original list.
- Make a loop that prints out all of the names in the copied list, along with a message that this is the copied list.
"""



"""#### Program 5: Write a python program for following

- Create a list to store the marks of top 15 students obtained by the students in Python Quiz held on 21/08/2018. Maximum marks=15
- Print the maximum marks obtained by the student from the list.
- Print the minimum marks obtained by the student.
- Find the sum of all the marks.
- Find the average of the marks.
- Reverse the original list and display using for loop.
"""



"""#### Program 6: Write a program in Python to create a list which contains n integers entered by the user and delete all odd numbers from the list. Example: If initial contents of the list is=[1,2,3,4,5,6,7,8,9,10], the output would be=[2,4,6,8,10]."""



"""## Optional Questions

#### Program 7: Write a python program for following.
- Create an initial empty list named "countries" 
- Read the names of n countries from the user and add them to country list:
- Use for loop to display all the names of the countries from the list and add "is Great" after the country name if it is "India"
"""



"""### Program 8: Write a Python program to find the list in a list of lists whose sum of elements is the highest.
Sample lists: [[1,2,3], [4,5,6], [10,11,12], [7,8,9]]
Expected Output: [10, 11, 12]
"""

